create database Retail_Customer_Behavior;
SHOW VARIABLES LIKE 'port';
use Retail_Customer_Behavior;
select * from retail_customers;

-- 1.What is the total revenue generated by male v female customers?
select gender,sum(purchase_amount) as Revenue 
from retail_customers 
group by gender;

-- 2.Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from retail_customers
where discount_applied="Yes" and purchase_amount>=(select avg(purchase_amount) from retail_customers);

-- 3.Which are the top5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as Avg_review_rating 
from retail_customers
group by item_purchased 
order by avg(review_rating)  desc limit 5;

-- 4.Compare the average purchase amounts between standard and express shipping
select shipping_type,avg(purchase_amount) As Avg_purchase_amount
from retail_customers
where shipping_type in ("Express","Standard")
group by shipping_type;
-- 5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non -subscribers
select subscription_status,
count(customer_id) as Total_Customers,
sum(purchase_amount) as Revenue , 
avg(purchase_amount) As Avg_spend 
from retail_customers 
group by subscription_status;
-- 6.Which 5 products have the highest percentage of purchases with discount applies?

select item_purchased,
round(100*(sum(case when discount_applied="Yes" then 1 else 0 end)/count(*)),2) as discount_rate
from retail_customers 
group by item_purchased
order by discount_rate desc
limit 5;

-- 7.Segment customers into new ,returning and loyal based on their total number of previous purchases and show the count of each Segment
select 
case 
when previous_purchases=1 then "NEW"
when previous_purchases between 2 and 10 then "RETURNING" 
else "LOYAL"
end  as Type_of_customers ,count(customer_id) as count from retail_customers
group by Type_of_customers; 
-- -----------------------------------------------
with customer_type as (select 
case 
when previous_purchases=1 then "NEW"
when previous_purchases between 2 and 10 then "RETURNING" 
else "LOYAL"
end  as Type_of_customers from retail_customers
)
select type_of_customers,count(*) as No_of_customers from customer_type group by type_of_customers;
-- 8.What are the top3 most purchased products with in each category
with item_count as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from retail_customers
group by category ,item_purchased
)
select item_rank,category,item_purchased,total_orders from item_count where item_rank<=3;

-- 9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status,
count(customer_id) as repeated_Number_of_purchases
from retail_customers	
where previous_purchases>5 
group by subscription_status;
-- 10.What is the revenue contribution of each age group
select age_group ,
sum(purchase_amount) as revenue
from retail_customers 
group by age_group
order by revenue desc;